name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_TOKEN }}
        shell: pwsh
        run: |
          Publish-Module -Path ./Module/K8sCredentialSpec -NuGetApiKey $env:NUGET_KEY -Verbose
