name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    steps:
      - uses: actions/checkout@v2
      - name: Publish Module to PowerShell Gallery
        uses: pcgeek86/publish-powershell-module-action@v19
        id: publish-module
        with:
          modulePath: Module/K8sCredentialSpec
          NuGetApiKey: ${{ secrets.NUGET_TOKEN }}
